FROM b4tman/squid:5.3
USER root
RUN apk add --no-cache perl
RUN apk add --no-cache perl-dbi
RUN apk add --no-cache perl-dbd-mysql
RUN apk add --no-cache php8
RUN apk add --no-cache php8-mysqlnd
RUN apk add --no-cache php8-mysqli
RUN apk add --no-cache php8-pdo
RUN apk add --no-cache php8-pdo_mysql
RUN apk add --no-cache php8-opcache
RUN apk add --no-cache php8-intl
USER squid
